version: 2.1

executors:
  board_app_django:
    working_directory: ~/board-app
    docker:
      - image: circleci/python:3.8.1
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: board
          #MYSQL_USER: user
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_ROOT_HOST: '%'
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

jobs:
  build-and-test:
    executor: board_app_django
    steps:
      - checkout
      - run: pip install -r dockerfile_requirements.txt
      - run:
          name: add db host
          command: |
            # Add '127.0.0.1 db' to /etc/host file. Then 'db' is used as a value of 'DB_HOST' name.
            echo 127.0.0.1 db | sudo tee -a /etc/hosts
      - run:
          command: |
            echo SECRET_KEY=${SECRET_KEY} > ~/board-app/src/.env
            echo DEBUG=${DEBUG} >> ~/board-app/src/.env
            echo ALLOWED_HOSTS=['*'] >> ~/board-app/src/.env
            echo DATABASE_URL=${DATABASE_URL} >> ~/board-app/src/.env
            echo MODE=${MODE} >> ~/board-app/src/.env
      - run:
          environment:
            DB_HOST: db
          command: |
            cd ./src
            tox

workflows:
  main:
    jobs:
      - build-and-test
