version: 2.1

executors:
  board_app_django:
    working_directory: ~/board-app
    docker:
      - image: circleci/python:3.8.1

jobs:
  build-and-test:
    executor: board_app_django
    steps:
      - checkout
      - run:
          command: |
            ls -al
            sudo docker-cpmpose run web tox

workflows:
  main:
    jobs:
      - build-and-test
