version: 2.1

executors:
  board_app_django:
    working_directory: ~/board-app
    docker:
      - image: circleci/python:3.8.1

jobs:
  build-and-test:
    executor: board_app_django
    steps:
      - checkout
      - run: pip install virtualenv
      - run: pip install tox
      - run:
          command: |
            cd ./src
            tox

workflows:
  main:
    jobs:
      - build-and-test
