version: 2.1

executors:
  board_app_django:
    working_directory: ~/board-app
    docker:
      - image: circleci/python:3.8.1
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: board
          MYSQL_USER: user
          MYSQL_PASSWORD: password

jobs:
  build-and-test:
    executor: board_app_django
    steps:
      - checkout
      - run: pip install -r dockerfile_requirements.txt
      - run:
          name: add db host
          command: |
            # Add '127.0.0.1 db' to /etc/host file. Then 'db' is used as a value of 'DB_HOST' name.
            echo 127.0.0.1 db | sudo tee -a /etc/hosts
      - run:
          command: |
            cd ./src
            tox

workflows:
  main:
    jobs:
      - build-and-test
