# Generated by Django 3.0.8 on 2020-11-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201017_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='Participant',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='eventcomment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='fee',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='participant',
            table='t_participant',
        ),
    ]
