# Generated by Django 3.0.8 on 2020-11-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_participant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
