# Generated by Django 3.0.8 on 2020-09-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200925_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='create_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='update_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='create_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='update_id',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='create_id',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='update_id',
        ),
    ]
