# Generated by Django 3.0.8 on 2020-09-26 12:50

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200925_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='candidate',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='history',
        ),
        migrations.AddField(
            model_name='candidate',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.event_image_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_icon_file_path),
        ),
    ]
