# Generated by Django 3.0.8 on 2020-11-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201114_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('0', 'Cancel'), ('1', 'Join')], default='1', max_length=10),
        ),
    ]
