# Generated by Django 3.0.8 on 2020-12-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event_is_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_publish',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('0', 'Private'), ('1', 'Publish'), ('2', 'Cancel')], default='0', max_length=10),
        ),
    ]
