# Generated by Django 3.0.8 on 2020-12-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201207_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_guide',
            field=models.BooleanField(default=False, verbose_name='guide status'),
        ),
    ]
