# Generated by Django 3.0.8 on 2020-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201211_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_time']},
        ),
        migrations.AlterModelOptions(
            name='eventcomment',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['updated_at']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='family name'),
        ),
    ]
