# Generated by Django 3.0.8 on 2020-12-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fee',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
