# Generated by Django 3.0.8 on 2020-12-14 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201214_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fee',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
