# Generated by Django 3.0.8 on 2021-01-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201214_2114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('event', 'user')},
        ),
    ]
