# Generated by Django 3.0.8 on 2021-02-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210210_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='status',
            field=models.CharField(choices=[('0', 'Default'), ('1', 'EDITED')], default='0', max_length=10),
        ),
    ]
